// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB599tG4TARmK5XX0qKuIH4RvaJJL6uF50',
    appId: '1:784150802180:android:c12ba4a1d9e7d1710e6a51',
    messagingSenderId: '784150802180',
    projectId: 'flutter-hadieaty-project',
    storageBucket: 'flutter-hadieaty-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPxVOhTu2eZff2nzkph-vMn4-8AqNdko',
    appId: '1:784150802180:ios:1031754afe1fb9ab0e6a51',
    messagingSenderId: '784150802180',
    projectId: 'flutter-hadieaty-project',
    storageBucket: 'flutter-hadieaty-project.firebasestorage.app',
    androidClientId: '784150802180-jrvue0tjfm0htt2lnvi07i2blhmmqjso.apps.googleusercontent.com',
    iosClientId: '784150802180-q71p05tnmkctc2k3pig5kmgkif8tkrt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
